export const cardWeek: string;
export const cardWeekHeader: string;
export const cardWeekBodyWrap: string;
export const cardWeekBody: string;
export const cardWeekItem: string;
export const cardWeekItemWeek: string;
export const cardWeekItemDate: string;
export const cardWeekItemSelected: string;
export const cardWeekItemSelectedText: string;